services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - backend
    deploy:
      replicas: 1

  auth:
    build: ../../services/auth
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
      - JWT_SECRET=your_jwt_secret
    networks:
      - backend
    depends_on:
      - rabbitmq
    deploy:
      replicas: 1

  router:
    build: ../../services/router
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
      - JWT_SECRET=your_jwt_secret
    networks:
      - backend
    depends_on:
      - rabbitmq
    deploy:
      replicas: 1

  route_checker:
    build: ../../services/route-checker
    environment:
      - PORT=3004
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    networks:
      - backend
    depends_on:
      - rabbitmq
    deploy:
      replicas: 1

  resource-x:
    build: ../../services/resource-x
    environment:
      - PORT=3000
    networks:
      - backend
    deploy:
      replicas: 1

  nginx:
    image: nginx:latest
    deploy:
      replicas: 1
    networks:
      - backend

networks:
  backend:
    driver: bridge
